<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/16 12:35:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
